[package]
name = "gpp-decrypt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8.4"
base64 = "0.13.0"
openssl = "0.10.35"